import "@/styles/globals.css";
import { Open_Sans } from "next/font/google";
import { TailwindIndicator } from "@/components/TailwindIndicator";

const inter = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Hyremi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="antialiased select-none">
      <body
        className={`${inter.className}`}
        style={{
          backgroundColor: "#f8f6f0",
        }}
      >
        {children}
        <TailwindIndicator />
      </body>
    </html>
  );
}
